namespace gnu.x11.keysym {


/**
 * Latin 1-specific keyboard symbols. Imported from
 * <code>XK_LATIN1</code> section of
 * <code>/usr/include/X11/X11/keysymdef.h</code>. 
 * Note that byte 3 = 0x00.
 */
public class Latin1 {
  public const int SPACE = 0x020;
  public const int EXCLAM = 0x021;
  public const int QUOTE_DBL = 0x022;
  public const int NUMBER_SIGN = 0x023;
  public const int DOLLAR = 0x024;
  public const int PERCENT = 0x025;
  public const int AMPERSAND = 0x026;
  public const int APOSTROPHE = 0x027;
  public const int QUOTE_RIGHT = 0x027; /* deprecated */
  public const int PAREN_LEFT = 0x028;
  public const int PAREN_RIGHT = 0x029;
  public const int ASTERISK = 0x02a;
  public const int PLUS = 0x02b;
  public const int COMMA = 0x02c;
  public const int MINUS = 0x02d;
  public const int PERIOD = 0x02e;
  public const int SLASH = 0x02f;
  public const int NUM_0 = 0x030;
  public const int NUM_1 = 0x031;
  public const int NUM_2 = 0x032;
  public const int NUM_3 = 0x033;
  public const int NUM_4 = 0x034;
  public const int NUM_5 = 0x035;
  public const int NUM_6 = 0x036;
  public const int NUM_7 = 0x037;
  public const int NUM_8 = 0x038;
  public const int NUM_9 = 0x039;
  public const int COLON = 0x03a;
  public const int SEMICOLON = 0x03b;
  public const int LESS = 0x03c;
  public const int EQUAL = 0x03d;
  public const int GREATER = 0x03e;
  public const int QUESTION = 0x03f;
  public const int AT = 0x040;
  public const int A = 0x041;
  public const int B = 0x042;
  public const int C = 0x043;
  public const int D = 0x044;
  public const int E = 0x045;
  public const int F = 0x046;
  public const int G = 0x047;
  public const int H = 0x048;
  public const int I = 0x049;
  public const int J = 0x04a;
  public const int K = 0x04b;
  public const int L = 0x04c;
  public const int M = 0x04d;
  public const int N = 0x04e;
  public const int O = 0x04f;
  public const int P = 0x050;
  public const int Q = 0x051;
  public const int R = 0x052;
  public const int S = 0x053;
  public const int T = 0x054;
  public const int U = 0x055;
  public const int V = 0x056;
  public const int W = 0x057;
  public const int X = 0x058;
  public const int Y = 0x059;
  public const int Z = 0x05a;
  public const int BRACKET_LEFT = 0x05b;
  public const int BACKSLASH = 0x05c;
  public const int BRACKET_RIGHT = 0x05d;
  public const int ASCII_CIRCUM = 0x05e;
  public const int UNDERSCORE = 0x05f;
  public const int GRAVE = 0x060;
  public const int QUOTE_LEFT = 0x060; /* deprecated */

  public const int A_SMALL = 0x061;
  public const int B_SMALL = 0x062;
  public const int C_SMALL = 0x063;
  public const int D_SMALL = 0x064;
  public const int E_SMALL = 0x065;
  public const int F_SMALL = 0x066;
  public const int G_SMALL = 0x067;
  public const int H_SMALL = 0x068;
  public const int I_SMALL = 0x069;
  public const int J_SMALL = 0x06a;
  public const int K_SMALL = 0x06b;
  public const int L_SMALL = 0x06c;
  public const int M_SMALL = 0x06d;
  public const int N_SMALL = 0x06e;
  public const int O_SMALL = 0x06f;
  public const int P_SMALL = 0x070;
  public const int Q_SMALL = 0x071;
  public const int R_SMALL = 0x072;
  public const int S_SMALL = 0x073;
  public const int T_SMALL = 0x074;
  public const int U_SMALL = 0x075;
  public const int V_SMALL = 0x076;
  public const int W_SMALL = 0x077;
  public const int X_SMALL = 0x078;
  public const int Y_SMALL = 0x079;
  public const int Z_SMALL = 0x07a;

  public const int BRACE_LEFT = 0x07b;
  public const int BAR = 0x07c;
  public const int BRACE_RIGHT = 0x07d;
  public const int ASCII_TILDE = 0x07e;

  public const int NO_BREAKSPACE = 0x0a0;
  public const int EXCLAM_DOWN = 0x0a1;
  public const int CENT = 0x0a2;
  public const int STERLING = 0x0a3;
  public const int CURRENCY = 0x0a4;
  public const int YEN = 0x0a5;
  public const int BROKEN_BAR = 0x0a6;
  public const int SECTION = 0x0a7;
  public const int DIAERESIS = 0x0a8;
  public const int COPYRIGHT = 0x0a9;
  public const int ORDFEMININE = 0x0aa;
  public const int GUILLEMOT_LEFT = 0x0ab; /* left angle quotation mark */
  public const int NOT_SIGN = 0x0ac;
  public const int HYPHEN = 0x0ad;
  public const int REGISTERED = 0x0ae;
  public const int MACRON = 0x0af;
  public const int DEGREE = 0x0b0;
  public const int PLUS_MINUS = 0x0b1;
  public const int TWO_SUPERIOR = 0x0b2;
  public const int THREE_SUPERIOR = 0x0b3;
  public const int ACUTE = 0x0b4;
  public const int MU = 0x0b5;
  public const int PARAGRAPH = 0x0b6;
  public const int PERIOD_CENTERED = 0x0b7;
  public const int CEDILLA = 0x0b8;
  public const int ONE_SUPERIOR = 0x0b9;
  public const int MASCULINE = 0x0ba;
  public const int GUILLEMOT_RIGHT = 0x0bb; /* right angle quotation mark */
  public const int ONE_QUARTER = 0x0bc;
  public const int ONE_HALF = 0x0bd;
  public const int THREE_QUARTERS = 0x0be;
  public const int QUESTION_DOWN = 0x0bf;
  public const int A_GRAVE = 0x0c0;
  public const int A_ACUTE = 0x0c1;
  public const int A_CIRCUMFLEX = 0x0c2;
  public const int A_TILDE = 0x0c3;
  public const int A_DIAERESIS = 0x0c4;
  public const int A_RING = 0x0c5;
  public const int AE = 0x0c6;
  public const int C_CEDILLA = 0x0c7;
  public const int E_GRAVE = 0x0c8;
  public const int E_ACUTE = 0x0c9;
  public const int E_CIRCUMFLEX = 0x0ca;
  public const int E_DIAERESIS = 0x0cb;
  public const int I_GRAVE = 0x0cc;
  public const int I_ACUTE = 0x0cd;
  public const int I_CIRCUMFLEX = 0x0ce;
  public const int I_DIAERESIS = 0x0cf;
  public const int E_TH = 0x0d0;
  public const int N_TILDE = 0x0d1;
  public const int O_GRAVE = 0x0d2;
  public const int O_ACUTE = 0x0d3;
  public const int O_CIRCUMFLEX = 0x0d4;
  public const int O_TILDE = 0x0d5;
  public const int O_DIAERESIS = 0x0d6;
  public const int MULTIPLY = 0x0d7;
  public const int O_OBLIQUE = 0x0d8;
  public const int O_SLASH = 0x0d9;
  public const int U_ACUTE = 0x0da;
  public const int U_CIRCUMFLEX = 0x0db;
  public const int U_DIAERESIS = 0x0dc;
  public const int Y_ACUTE = 0x0dd;
  public const int T_HORN = 0x0de;
  public const int S_SHARP = 0x0df;

  public const int A_GRAVE_SMALL = 0x0e0;
  public const int A_ACUTE_SMALL = 0x0e1;
  public const int A_CIRCUMFLEX_SMALL = 0x0e2;
  public const int A_TILDE_SMALL = 0x0e3;
  public const int A_DIAERESIS_SMALL = 0x0e4;
  public const int A_RING_SMALL = 0x0e5;
  public const int AE_SMALL = 0x0e6;
  public const int C_CEDILLA_SMALL = 0x0e7;
  public const int E_GRAVE_SMALL = 0x0e8;
  public const int E_ACUTE_SMALL = 0x0e9;
  public const int E_CIRCUMFLEX_SMALL = 0x0ea;
  public const int E_DIAERESIS_SMALL = 0x0eb;
  public const int I_GRAVE_SMALL = 0x0ec;
  public const int I_ACUTE_SMALL = 0x0ed;
  public const int I_CIRCUMFLEX_SMALL = 0x0ee;
  public const int I_DIAERESIS_SMALL = 0x0ef;
  public const int E_TH_SMALL = 0x0f0;
  public const int N_TILDE_SMALL = 0x0f1;
  public const int O_GRAVE_SMALL = 0x0f2;
  public const int O_ACUTE_SMALL = 0x0f3;
  public const int O_CIRCUMFLEX_SMALL = 0x0f4;
  public const int O_TILDE_SMALL = 0x0f5;
  public const int O_DIAERESIS_SMALL = 0x0f6;
  public const int DIVISION_SMALL = 0x0f7;
  public const int O_SLASH_SMALL = 0x0f8;
  public const int O_OBLIQUE_SMALL = 0x0f9;
  public const int UA_CUTE_SMALL = 0x0fa;
  public const int U_CIRCUMFLEX_SMALL = 0x0fb;
  public const int U_DIAERESIS_SMALL = 0x0fc;
  public const int YA_CUTE_SMALL = 0x0fd;
  public const int T_HORN_SMALL = 0x0fe;
  public const int Y_DIAERESIS_SMALL = 0x0ff;
}

}
